name: Generate Documentation

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use to build and test the package."
                required: false
                type: string
                default: "5.6.3"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""
        secrets:
            TOKEN:
                required: true
            DEPLOYSSHSECRET:
                required: true

jobs:

  docs:
    runs-on: ubuntu-20.04

    steps:
        - name: Install Packages
          if: inputs.packages-to-install != ''
          run: |
              sudo apt install -y ${{ inputs.packages-to-install }}

        - uses: gilmourspace/install-swift@v1
          with:
              swift-version: ${{ inputs.swift-version }}

        - name: Setup SSH Key
          uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

        - name: Clone Repo 
          uses: actions/checkout@v3

        - name: Generate Documentation
          uses: mipalgu/swiftpm-generate-documentation@main
          with:
              swift-version: ${{ inputs.swift-version }}
              hosting-base-path: "/"

        - name: Pages Deployment
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.TOKEN }}
              publish_dir: ./docs
              force_orphan: true
