name: Ubuntu 20.04 Swift CI

on:
    workflow_call:
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

  linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
            swift-version: "5.6"

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Debug Build
        run: swift build -c debug

      - name: Release build
        run: swift build -c release

      - name: Debug Test
        run: swift test --enable-code-coverage

      - name: Release Test
        run: swift test -c release
