name: Ubuntu 20.04 Swift CI

on:
    workflow_call:
        secrets:
            DEPLOYSSHSECRET:
                required: true
            DEPLOYSSHPUBLICKEY:
                required: true

jobs:

  exec-ci:
    runs-on: ubuntu-20.04

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
            swift-version: "5.6"

      - name: Setup SSH Key
        run: | 
            rm -rf ~/.ssh
            mkdir -m 0700 ~/.ssh
            echo "${{ secrets.DEPLOYSSHSECRET }}" > ~/.ssh/id_ed25519
            echo "${{ secrets.DEPLOYSSHPUBLICKEY }}" > ~/.ssh/id_ed25519.pub
            chmod 0600 ~/.ssh/id_ed25519
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519

      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Debug Build
        run: swift build -c debug

      - name: Release build
        run: swift build -c release

      - name: Debug Test
        run: swift test --enable-code-coverage

      - name: Release Test
        run: swift test -c release
