name: MacOS Monterey Swift CI

on:
    workflow_call:
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

    setup:
        runs-on: macos-12
        steps:
            - uses: swift-actions/setup-swift@v1
              with:
                swift-version: "5.6"

            - name: Setup SSH Key
              uses: webfactory/ssh-agent@v0.5.4
              with:
                ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

    build-debug:
        needs: setup
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3

            - name: Debug Build
              run: xcrun --toolchain "/Users/runner/hostedtoolcache/swift-macOS/5.6.3/x64" swift build -c debug

    build-release:
        needs: setup
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3

            - name: Release build
              run: xcrun --toolchain "/Users/runner/hostedtoolcache/swift-macOS/5.6.3/x64" swift build -c release

    test-debug:
        needs: build-debug
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3

            - name: Debug Test
              run: xcrun --toolchain "/Users/runner/hostedtoolcache/swift-macOS/5.6.3/x64" swift test

    test-release:
        needs: build-release
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3

            - name: Release Test
              run: xcrun --toolchain "/Users/runner/hostedtoolcache/swift-macOS/5.6.3/x64" swift test -c release
