name: Swift Coverage Test

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use to build and test the package."
                required: false
                type: string
                default: "5.9.1"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""
            minimum-coverage:
                description: The minumum code coverage that the package should test.
                required: false
                type: number
                default: 80
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

  coverage:
        uses: ./.github/workflows/linux-docker-coverage-swift.yml
        with:
            swift-version: ${{ inputs.swift-version }}
            packages-to-install: ${{ inputs.packages-to-install }}
            minimum-coverage: ${{ inputs.minimum-coverage }}
        secrets: inherit
