name: Generate Documentation

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use to build and test the package."
                required: false
                type: string
                default: "5.6.3"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""
        secrets:
            TOKEN:
                required: true
            DEPLOYSSHSECRET:
                required: true

jobs:

  docs:
      uses: ./.github/workflows/linux-github-docs-swift.yml
      with:
          swift-version: ${{ inputs.swift-version }}
          packages-to-install: ${{ inputs.packages-to-install }}
      secrets: inherit
