name: Install Swift
description: Installs a swift release

runs:
    using: 'composite'

    steps:
        - name: Install Swift (Windows)
          if: ${{ runner.os == 'Windows' }}
          uses: compnerd/gha-setup-swift@main
          with:
              branch: swift-5.6.3-release
              tag: 5.6-RELEASE

        - name: Install Swift (Linux)
          if: ${{ runner.os == 'Linux' }}
          uses: swift-actions/setup-swift@v1
          with:
            swift-version: "5.6"

        - name: Install Swift (macOS)
          if: ${{ runner.os == 'macOS' }}
          uses: swift-actions/setup-swift@v1
          with:
            swift-version: "5.6"
