name: Lint Swift

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use when linting the swift package."
                required: false
                type: string
                default: "5.6.3"
            swift-format-ref:
                description: "The ref to use when checking out swift-format"
                required: false
                type: string
                default: "swift-5.6.3-RELEASE"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""

jobs:

  lint:
      uses: ./.github/workflows/linux-native-lint-swift.yml
      secrets: inherit
