name: Lint Swift

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:

  swiftlint:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v2

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
            args: --strict

  swiftformat:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v2

      - name: Install Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.6"

      - name: Install swift-format
        uses: mipalgu/install-swift-format@main
        with:
          ref: swift-5.6.3-RELEASE

      - name: SwiftFormat
        run: swift-format lint -rs --configuration .swiftformat.json Sources Tests
