name: Ubuntu 20.04 Swift CI

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use to build and test the package."
                required: false
                type: string
                default: "5.6.3"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

    setup:
        runs-on: ubuntu-20.04
        steps:
            - name: Install Packages
              if: inputs.packages-to-install != ''
              run: |
                  sudo apt install -y ${{ inputs.packages-to-install }}

            - uses: gilmourspace/install-swift@v1
              with:
                  swift-version: ${{ inputs.swift-version }}


    build-debug:
        needs: setup
        runs-on: ubuntu-20.04
        steps:
            - name: Install Packages
              if: inputs.packages-to-install != ''
              run: |
                  sudo apt install -y ${{ inputs.packages-to-install }}

            - name: Setup SSH Key
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Debug Build
              run: swift build -c debug

    build-release:
        needs: setup
        runs-on: ubuntu-20.04
        steps:
            - name: Setup SSH Key
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Release Build
              run: swift build -c release

    test-debug:
        needs: setup
        runs-on: ubuntu-20.04
        steps:
            - name: Setup SSH Key
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Debug Test
              run: swift test --enable-code-coverage

    test-release:
        needs: setup
        runs-on: ubuntu-20.04
        steps:
            - name: Setup SSH Key
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Release Test
              run: swift test -c release
