name: Swift Coverage Test

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use to build and test the package."
                required: false
                type: string
                default: "5.6.3"
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

  coverage:
    runs-on: ubuntu-20.04

    steps:
        - uses: gilmourspace/install-swift@v1
          with:
            swift-version: ${{ inputs.swift-version }}

        - uses: gilmourspace/swift-coverage@v1
          with:
            ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }}
