name: Embedded C Docker Lint

on:
    workflow_call:

jobs:

  cppcheck:
    runs-on: [docker]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Lint
        run: |
            mkdir cfg-cppcheck-build-dir
            cppcheck --project=cfg.cppcheck --enable=warning --enable=style --enable=performance --enable=portability --inline-suppr  --error-exitcode=1
