name: Linux Docker Lint

on:
  workflow_call:

jobs:

  swiftlint:
    runs-on: [linux, gspace]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:latest
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.WORKFLOW_PAT }}
    steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint lint --strict --no-cache

  swift-format:
    runs-on: [linux, gspace]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:latest
      credentials:
        username: ${{ secets.WORKFLOW_USERNAME }}
        password: ${{ secrets.WORKFLOW_PAT }}
    steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swift-format lint -rs --ignore-unparsable-files --configuration .swiftformat.json Sources Tests 
