name: Swift Coverage Test

on:
    workflow_call:
        inputs:
            minimum-coverage:
                description: The minumum code coverage that the package should test.
                required: false
                type: number
                default: 80

jobs:

  coverage:
    runs-on: [linux, gspace]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Run tests
          run: swift test --enable-code-coverage

        - name: Coverage Test
          id: cov
          run: |
            OUTPUT=$(swift-test-codecov --minimum=${{ inputs.minimum-coverage }} --no-dependencies --no-tests -p table --exclude-path Tests .build/debug/codecov/*.json)
            echo $OUTPUT >> $GITHUB_STEP_SUMMARY
            if [ $? -eq 0 ]; then
              COV=$(echo "$output" | grep ":" | head | cut -d":" -f2 | sed 's/^ //' | sed 's/%//g')
              echo "**Coverage test passed: $COV**" >> $GITHUB_STEP_SUMMARY
            else
              COV=$(echo "$output" | grep ":" | head | cut -d":" -f2 | sed 's/^ //' | sed 's/%//g')
              echo "**Coverage test failed: $COV**" >> $GITHUB_STEP_SUMMARY
              exit 1
            fi
