name: Lint Swift

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use when linting the swift package."
                required: false
                type: string
                default: "5.6.3"
            swift-format-ref:
                description: "The ref to use when checking out swift-format"
                required: false
                type: string
                default: "swift-5.6.3-RELEASE"

jobs:

  swiftlint:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
            args: --strict

  swiftformat:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v3

      - name: Install Swift
        uses: gilmourspace/install-swift@v1
        with:
          swift-version: ${{ inputs.swift-version }}

      - name: Install swift-format
        uses: mipalgu/install-swift-format@main
        with:
          ref: ${{ inputs.swift-format-ref }}

      - name: SwiftFormat
        run: swift-format lint -rs --configuration .swiftformat.json Sources Tests
