name: Lint Swift

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use when linting the swift package."
                required: false
                type: string
                default: "5.6.3"
            swift-format-ref:
                description: "The ref to use when checking out swift-format"
                required: false
                type: string
                default: "swift-5.6.3-RELEASE"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""

jobs:

    swiftlint:
        runs-on: ubuntu-20.04
        steps:
            - name: Install Packages
              if: inputs.packages-to-install != ''
              run: |
                  sudo apt install -y ${{ inputs.packages-to-install }}

            - name: Clone Repo 
              uses: actions/checkout@v3

            - name: SwiftLint
              uses: norio-nomura/action-swiftlint@3.2.1
              with:
                  args: --strict

    swiftformat:
        runs-on: ubuntu-20.04
        steps:
            - name: Install Packages
              if: inputs.packages-to-install != ''
              run: |
                  sudo apt install -y ${{ inputs.packages-to-install }}

            - name: Clone Repo 
              uses: actions/checkout@v3

            - name: Install Swift
              uses: gilmourspace/install-swift@v1
              with:
                  swift-version: ${{ inputs.swift-version }}

            - name: SwiftFormat
              run: swift-format lint -rs --configuration .swiftformat.json Sources Tests
