name: Generate Documentation

on:
    workflow_call:
        secrets:
            TOKEN:
                required: true
            DEPLOYSSHSECRET:
                required: true

jobs:

  docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
            swift-version: "5.6"

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }} 

      - name: Clone Repo 
        uses: actions/checkout@v2

      - name: Generate Documentation
        uses: mipalgu/swiftpm-generate-documentation@main
        with:
            swift-version: "5.6"
            hosting-base-path: "/"

      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs
          force_orphan: true
