name: Swift Coverage Test

on:
    workflow_call:
        inputs:
            minimum-coverage:
                description: The minumum code coverage that the package should test.
                required: false
                type: number
                default: 80

jobs:

  coverage:
    runs-on: [docker]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Setup SSH Key
          uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }}

        - name: Run tests
          run: swift test --enable-code-coverage

        - name: Coverage Test
          id: cov
          run: |
            swift-test-codecov --minimum=${{ inputs.minimum-coverage }} --no-dependencies --no-tests -p table --exclude-path Tests .build/debug/codecov/*.json
