name: Linux Docker Lint

on:
  workflow_call:

jobs:

  swiftlint:
    runs-on: [docker]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint lint --strict --no-cache

  swift-format:
    runs-on: [docker]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run SwiftFormat
        run: swift-format lint -rs --ignore-unparsable-files --configuration .swiftformat.json Sources Tests
