name: Linux Swift CI

on:
    workflow_call:
        inputs:
            swift-version:
                description: "The swift version to use to build and test the package."
                required: false
                type: string
                default: "5.9.1"
            packages-to-install:
                description: "A list of packages to install before running the workflow."
                required: false
                type: string
                default: ""
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

    ci:
        uses: ./.github/workflows/linux-docker-swift.yml
        with:
            swift-version: ${{ inputs.swift-version }}
            packages-to-install: ${{ inputs.packages-to-install }}
        secrets: inherit
