name: Ubuntu 20.04 Swift Native

on:
    workflow_call:

defaults:
    run:
        shell: bash -leo pipefail {0}

jobs:

  ci:
    runs-on: linux-amd64

    steps:

      - name: Delete Everything
        run: rm -rf *

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clear Cache
        run: |
            swift package purge-cache || true
            swift package reset
            swift package clean

      - name: Debug Build
        run: |
            swift build -c debug

      - name: Release build
        run: |
            swift build -c release

      - name: Debug Test
        run: |
            swift test

      - name: Release Test
        run: |
            swift test -c release
