name: Linux Docker Lint

on:
  workflow_call:

jobs:

  swiftlint:
    runs-on: [linux, gspace]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: |
          echo $(swiftlint lint --strict --no-cache) >> $GITHUB_STEP_SUMMARY
          if [ $? -ne 0 ]; then
            exit 1
          fi

  swift-format:
    runs-on: [linux, gspace]
    container:
      image: ghcr.io/gilmourspace/gspaceenv:0
      credentials:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.CONTAINER_PAT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run SwiftFormat
        run: |
          echo $(swift-format lint -rs --ignore-unparsable-files --configuration .swiftformat.json Sources Tests) >> $GITHUB_STEP_SUMMARY
          if [ $? -ne 0 ]; then
            exit 1
          fi
