name: Swift Coverage Test

on:
    workflow_call:

defaults:
    run:
        shell: bash -leo pipefail {0}

jobs:

  coverage:
    runs-on: cpslab

    steps:

        - name: Delete Everything
          run: rm -rf *

        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Clear Cache
          run: |
              swift package purge-cache || true
              swift package reset
              swift package clean

        - name: Run tests
          run: swift test --enable-code-coverage

        - name: Coverage Test
          id: cov
          run: |
            cov=`swift-test-codecov -p table .build/debug/codecov/*.json | grep ":" | head | cut -d":" -f2 | sed 's/^ //'`
            echo "{codecov}={$cov}" >> $GITHUB_OUTPUT
            [[ cov -gte 80 ]]

        - name: Post Positive Result
          if: ${{ success() }}
          run: |
            echo "::warning file=Package.swift,line=1,col=1::The current code coverage percentage is passing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."

        - name: Post Negative Result
          if: ${{ failure() }}
          run: |
            echo "::error file=Package.swift,line=1,col=1::The current code coverage percentage is failing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."
