name: Swift Coverage Test

on:
    workflow_call:
        secrets:
            DEPLOYSSHSECRET:
                required: true

jobs:

  coverage:
    runs-on: macOS-12

    steps:
        - uses: gilmourspace/install-swift@v1

        - uses: gilmourspace/swift-coverage@v1
          with:
            ssh-private-key: ${{ secrets.DEPLOYSSHSECRET }}
