name: Linux Swift Cross Compilation

on:
    workflow_call:

defaults:
    run:
        shell: bash -ileo pipefail {0}

jobs:

  exec-cross:
    runs-on: cross-armv7-linux-gnueabihf

    steps:
      
      - name: Delete Everything
        run: rm -rf *

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clear Cache
        run: |
            swift package purge-cache || true
            swift package reset
            swift package clean

      - name: Debug Test (Linux host)
        if: if: ${{ runner.os == 'Linux' }}
        run: |
            PKG_CONFIG_PATH="/usr/local/armv7-unknown-linux-gnueabihf/staging/lib/pkgconfig:${PKG_CONFIG_PATH}" swift build --build-tests --destination /usr/local/armv7-unknown-linux-gnueabihf/destination.json
            scp .build/armv7-unknown-linux-gnueabihf/debug/${{ github.event.repository.name }}PackageTests.xctest runner@arty.local:~
            ssh runner@arty.local bash -ic /home/runner/${{ github.event.repository.name}}PackageTests.xctest 
            ssh runner@arty.local rm ${{ github.event.repository.name }}PackageTests.xctest

      - name: Debug Test (macOS host)
        if: ${{ runner.os == 'macOS' }}
        run: |
            PKG_CONFIG_PATH="/usr/local/armv7-unknown-linux-gnueabihf/staging/lib/pkgconfig:${PKG_CONFIG_PATH}" xcrun --toolchain org.cpslab swift build --build-tests --destination /usr/local/armv7-unknown-linux-gnueabihf/destination.json
            scp .build/armv7-unknown-linux-gnueabihf/debug/${{ github.event.repository.name }}PackageTests.xctest runner@arty.local:~
            ssh runner@arty.local bash -ic /home/runner/${{ github.event.repository.name}}PackageTests.xctest 
            ssh runner@arty.local rm ${{ github.event.repository.name }}PackageTests.xctest
